services:
  core-service-api:
    build:
      context: .
      dockerfile: ./Core-Service.API/Dockerfile
    ports:
      - "8050:8050"
    networks:
      - foodstock-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    image: core-service-api:latest

  shopping-service-api:
    build:
      context: .
      dockerfile: ./Shopping-Service.API/Dockerfile
    ports:
      - "8060:8060"
    networks:
      - foodstock-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    image: shopping-service-api:latest

  core-service-ui:
    build:
      context: .
      dockerfile: ./Core-Service.UI/Dockerfile
    ports:
      - "8060:80"
    networks:
      - foodstock-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    image: core-service-ui:latest

networks:
  foodstock-network:
    driver: bridge
