services:

  core-service-ui:
    build:
      context: .
      dockerfile: ./Core-Service.UI/Dockerfile
    ports:
      - "8060:80"
    networks:
      - foodstock-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    image: core-service-ui:latest
    
  core-service-api:
    build:
      context: .
      dockerfile: ./Core-Service.API/Dockerfile
    ports:
      - "8050:8050"
    networks:
      - foodstock-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    image: core-service-api:latest

  shopping-service-api:
    build:
      context: .
      dockerfile: ./Shopping-Service.API/Dockerfile
    ports:
      - "8070:8070"
    networks:
      - foodstock-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    image: shopping-service-api:latest

  consumption-service-api:
    build:
      context: .
      dockerfile: ./Consumption-Service.API/Dockerfile
    ports:
      - "8075:8075"
    networks:
      - foodstock-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    image: consumption-service-api:latest
  
  report-service-api:
    build:
      context: .
      dockerfile: ./Report-Service.API/Dockerfile
    ports:
      - "8090:8090"
    networks:
      - foodstock-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    image: report-service-api:latest

networks:
  foodstock-network:
    driver: bridge
