// <auto-generated />
using System;
using FoodStock.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(EFCoreContext))]
    partial class EFCoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("FoodStock.Models.CategoryModel", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FoodStock.Models.ItemModel", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemDescription")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<float>("Measure")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("SpoilDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemID");

                    b.HasIndex("StockID");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("FoodStock.Models.StockModel", b =>
                {
                    b.Property<int>("StockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryModelCategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeasureType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Quantity")
                        .HasColumnType("REAL");

                    b.HasKey("StockID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("CategoryModelCategoryID");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("FoodStock.Models.ItemModel", b =>
                {
                    b.HasOne("FoodStock.Models.StockModel", "Stock")
                        .WithMany("Items")
                        .HasForeignKey("StockID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("FoodStock.Models.StockModel", b =>
                {
                    b.HasOne("FoodStock.Models.CategoryModel", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FoodStock.Models.CategoryModel", null)
                        .WithMany("Stocks")
                        .HasForeignKey("CategoryModelCategoryID");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FoodStock.Models.CategoryModel", b =>
                {
                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("FoodStock.Models.StockModel", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
